version: "3.9"

name: npm
volumes:
    letsencrypt_data: {}
    npm_data: {}
    db_data: {}

networks:
  npm:
    name: npm
    driver: bridge

services:
  npm-web:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm-secure
    networks:
      - npm
    ports:
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm-admin"
      DB_MYSQL_PASSWORD: "F5taYWxvHTzjtqxjHF"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - letsencrypt_data:/etc/letsencrypt
    depends_on:
      - db
  db:
    container_name: npm-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'vTWTxaWiBxB4oh4q3B'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm-admin'
      MYSQL_PASSWORD: 'F5taYWxvHTzjtqxjHF'
    volumes:
      -  db_data:/var/lib/mysql
    networks:
      - npm