version: "3.9"

name: npm
volumes:
    letsencrypt_data: {}
    npm_data: {}
    db_data: {}

networks:
  npm_proxy:
    name: npm_proxy
    driver: bridge

secrets:
 #nginx-proxy-manager
  mysql_pwd:
    file: $SECRETSDIR/NPM_MYSQL_PWD
  db_root_pwd:
    file: $SECRETSDIR/NPM_DB_ROOT_PWD

services:
  #nginx-proxy-manager
  npm-web:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm-secure
    networks:
      - npm_proxy
    ports:
      - '443:443'
      - '81:81'
      #- '80:80'
    secrets: [mysql_pwd]
    environment:
      DB_MYSQL_PASSWORD__FILE: /run/secrets/mysql_pwd
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm-admin"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - $DOCKERDIR/logs/npm:/data/logs
      - npm_data:/data
      - letsencrypt_data:/etc/letsencrypt
    depends_on:
      - db
      
  #db nginx-proxy-manager
  db:
    container_name: npm-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    secrets: [db_root_pwd, mysql_pwd]
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/db_root_pwd
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm-admin'
      MYSQL_PASSWORD__FILE: /run/secrets/mysql_pwd
    volumes:
      -  db_data:/var/lib/mysql
    networks:
      - npm_proxy