filenames:
  - /var/log/auth.log
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/ufw.log
labels:
  type: syslog
---
filenames:
  - /logs/traefik/*.log
labels:
  type: traefik
---
filenames:
  - /data/logs/*.log
labels:
  type: nginx-proxy-manager
